variables:
  PROJECT: "Ursip"
  DEV_NAMESPACE: "ursip-develop"
  STAGE_NAMESPACE: "ursip-internal"
  APP: "design-new"

before_script:
  - export DATE_ENV=$(date +'%d-%m-%Y')

stages:
  - build
  - deploy

cache:
  untracked: true
  paths:
    - node_modules/

Build:
  stage: build
  before_script:
    - yarn
  only:
    - master
  script:
    - CI="" yarn build
  artifacts:
    paths:
    - build/

Deploy:
  stage: deploy
  only:
    - master
  before_script:
    - "sed -i \"s|\\\"main\\\": \\\"src|\\\"main\\\": \\\"build|g\" packages/atoms/package.json"
    - "sed -i \"s|\\\"module\\\": \\\"src|\\\"module\\\": \\\"build|g\" packages/atoms/package.json"
    - "sed -i \"s|\\\"main\\\": \\\"src|\\\"main\\\": \\\"build|g\" packages/cells/package.json"
    - "sed -i \"s|\\\"module\\\": \\\"src|\\\"module\\\": \\\"build|g\" packages/cells/package.json"
    - "sed -i \"s|\\\"main\\\": \\\"src|\\\"main\\\": \\\"build|g\" packages/molecules/package.json"
    - "sed -i \"s|\\\"module\\\": \\\"src|\\\"module\\\": \\\"build|g\" packages/molecules/package.json"
    - "sed -i \"s|\\\"main\\\": \\\"src|\\\"main\\\": \\\"build|g\" packages/theme/package.json"
    - "sed -i \"s|\\\"module\\\": \\\"src|\\\"module\\\": \\\"build|g\" packages/theme/package.json"
    - "sed -i \"s|\\\"main\\\": \\\"src|\\\"main\\\": \\\"build|g\" packages/utils/package.json"
    - "sed -i \"s|\\\"module\\\": \\\"src|\\\"module\\\": \\\"build|g\" packages/utils/package.json"
    - CI="" yarn deploy-storybook
    - TMPDIR=$(ssh suadm@192.168.13.46 "mktemp -d")
  script:
    - yarn make-oao-nexus
    - scp -r .out/* suadm@192.168.13.46:$TMPDIR
    - ssh suadm@192.168.13.46 "sudo /opt/deploy front $PROJECT $STAGE_NAMESPACE $APP $TMPDIR"
