import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faBeer,
  faCog,
  faSpinner,
  faCheck,
  faChevronUp,
  faChevronDown,
  faQuestionCircle,
  faCaretDown,
  faEdit,
  faSave,
  faPlusCircle,
  faMinusCircle,
  faEllipsisV,
  faEllipsisH,
  faTimes,
  faTrash,
  faPencilAlt,
  faSearch,
  faUserCircle,
  faTrashAlt,
  faPlus,
  faQuestion,
  faMinus,
} from '@fortawesome/free-solid-svg-icons'
// import { faQuestionCircle } from '@fortawesome/free-regular-svg-icons'

library.add(
  faBeer,
  faCog,
  faSpinner,
  faCheck,
  faChevronUp,
  faChevronDown,
  faQuestionCircle,
  faQuestion,
  faCaretDown,
  faEdit,
  faSave,
  faPlus,
  faMinus,
  faPlusCircle,
  faMinusCircle,
  faEllipsisV,
  faEllipsisH,
  faTimes,
  faTrash,
  faTrashAlt,
  faPencilAlt,
  faSearch,
  faUserCircle,
)

export default library
